### ISSUE TITLE
Donkey Kong 64 no longer boots

### ISSUE THREAD

**Issue by Zapeth** [n64dev/cen64#209]
Boot logos and are displayed (N64/Rare/Dolby), but it just shows a black screen afterwards (no rap cutscene), tested with windows builds of d6b5b043956af205d5f6d28eb321ca796adfa021 and 3f865dcedf54384a06a7a2093bed740ad593d5b3

It does boot with an older build though (tested with an exe from 2017 that I had lying around, probably tag v0.3 but dont know for sure).

I tried bisecting it but for some reason I cant build with older commits (a bunch of `multiple definition of 'bus'; controller.c.obj` linker errors).

Curiously I'm having the same issue with a custom mupen64plus configuration right now (I had it working there with an older configuration/build as well), though its pretty difficult to pinpoint the origin due to the number of possible culprits.

**Comment by sp1187** [comment]
The `multiple definition to 'bus'` linking error is due to newer compilers (GCC 10 and forward) being more strict when multiple definitions of global variables exist, this can be disabled by adding `-fcommon` to CFLAGS if you wish to bisect further.

**Comment by Zapeth** [comment]
Thanks, that solved the compilation issue. Bisect seems to point to 9c5c5bb1fbf8aa3afa5eb203d69daf42cabd944a being the first bad commit.
